GET http://localhost:4000/user-api/users

### read req by obj id
GET http://localhost:4000/user-api/users/697f2364ba2ce879a9ba65df
###
POST http://localhost:4000/user-api/users 
Content-Type: application/json

{
    "username":"AnilB",
    "password":"Anil",
    "age":22
}

###
PUT http://localhost:4000/user-api/users/697f488fb42b6605cb692f71
Content-Type: application/json

{
  "username":"AnilB",
  "password":"bhar",
  "age":22
}

###delete user by objId
DELETE http://localhost:4000/user-api/users/697f2364ba2ce879a9ba65df






###
GET http://localhost:4000/product-api/products

###
POST http://localhost:4000/product-api/products
Content-Type: application/json

{
    "prodId": 200,
    "prodName":"Carr",
    "price":29000
}

###
GET http://localhost:4000/product-api/products/697f2c5136ed5eb7c9847828

###
PUT http://localhost:4000/product-api/products/697f4953b42b6605cb692f78
Content-Type: application/json

{
    "prodId": 200,
    "prodName":"Bike",
    "price":77000
}

###
DELETE http://localhost:4000/product-api/products/697f49cfb42b6605cb692f7d